# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'air.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import client
import asyncio


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("AirGO1.0")
        Dialog.resize(797, 600)
        self.bdwidget = QtWidgets.QWidget(Dialog)
        self.bdwidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bdwidget.setStyleSheet("QWidget#bdwidget{\n"
"background-color:rgb(0, 0, 0)}")
        self.bdwidget.setObjectName("bdwidget")
        self.label1 = QtWidgets.QLabel(self.bdwidget)
        self.label1.setGeometry(QtCore.QRect(280, 440, 201, 101))
        self.label1.setStyleSheet("\n"
"font: 7 20pt \"Poppins Light\" ;color: #FFFFFF\n"
"")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.pushButton1 = QtWidgets.QPushButton(self.bdwidget)
        self.pushButton1.setGeometry(QtCore.QRect(260, 230, 251, 71))
        self.pushButton1.setStyleSheet("QPushButton {\n"
"    background-color: #0C9BC0;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    font-size: 20pt;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FFFFFF;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0066CC;\n"
"}\n"
"\n"
"")
        self.pushButton1.setObjectName("pushButton1")
        self.label2 = QtWidgets.QLabel(self.bdwidget)
        self.label2.setGeometry(QtCore.QRect(270, 80, 231, 91))
        self.label2.setText("")
        self.label2.setPixmap(QtGui.QPixmap("C:\\Users\LAPTOP-ISHAN\Desktop\Project\GUI\Logo light.png"))
        self.label2.setScaledContents(True)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.bdwidget)
        self.label3.setGeometry(QtCore.QRect(280, 520, 451, 101))
        self.label3.setStyleSheet("\n"
"font: 7 8pt \"Poppins Light\" ;color: #FFFFFF\n"
"")
        self.label3.setObjectName("label3")
        self.pushButton2 = QtWidgets.QPushButton(self.bdwidget)
        self.pushButton2.setGeometry(QtCore.QRect(260, 330, 251, 71))
        self.pushButton2.setStyleSheet("QPushButton {\n"
"    background-color: #FF0022;\n"
"    color: white;\n"
"    border-radius: 25px;\n"
"    font-size: 20pt;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #FFFFFF;\n"
"    color: black;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0066CC;\n"
"}\n"
"\n"
"")
        self.pushButton2.setObjectName("pushButton2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Air", "AirGO_1.0"))
        self.label1.setText(_translate("Dialog", "         "))
        self.pushButton1.setText(_translate("Dialog", "Connect"))
        self.label3.setText(_translate("Dialog", "© All rights reserved. AIRGOVM 1.0"))
        self.pushButton2.setText(_translate("Dialog", "Disconnect"))
        self.pushButton1.clicked.connect(self.clicked1)
        self.pushButton2.clicked.connect(self.clicked2)

    def clicked1(self):
        if client.connect == 1:
            self.label1.setText("Connected")
            self.update()
        asyncio.run(client.main())

    def clicked2(self):
        if client.connect == 1:
            self.label1.setText("Disonnected")
            client.connect = 0
            client.dis = 1
            self.update()
        else:
            self.label1.setText("Disconnected")
            self.update()

    def update(self):
        self.label1.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
